apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees-management
  labels:
    app: employees-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees-management
  template:
    metadata:
      labels:
        app: employees-management
    spec:
      containers:
      - name: employees-management
        image: fatimadev/employeesmanagement:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: employees-management-service
spec:
  type: NodePort
  selector:
    app: employees-management
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30100
